import {
  createMessage,
  type AgentConfig,
  type AgentState,
  type ContentBlock,
  type Message,
  type ToolDefinition,
  type ToolResultBlock,
} from "./shared";
import { OptimisticMergeAgent } from "./s16";

type ErrorCategory = "Transient" | "Filesystem" | "Validation" | "Permission" | "Tooling" | "Unknown";

interface ErrorTask {
  error_task_id: string;
  title: string;
  description: string;
  category: ErrorCategory;
  source: string;
  status: "open" | "resolved";
  created_at: number;
  budget_index: number;
  over_budget: boolean;
}

interface ErrorDecision {
  category: ErrorCategory;
  consumed: number;
  remaining: number;
  overBudget: boolean;
}

class ErrorPolicy {
  private readonly budget: number;
  private consumed = 0;

  constructor(budget = 20) {
    this.budget = Math.max(1, Math.floor(budget));
  }

  categorize(message: string): ErrorCategory {
    const text = message.toLowerCase();

    if (
      text.includes("rate limit") ||
      text.includes("timeout") ||
      text.includes("temporar") ||
      text.includes("econnreset")
    ) {
      return "Transient";
    }

    if (
      text.includes("file not found") ||
      text.includes("path") ||
      text.includes("workspace") ||
      text.includes("old_text not found")
    ) {
      return "Filesystem";
    }

    if (
      text.includes("required") ||
      text.includes("invalid") ||
      text.includes("schema") ||
      text.includes("json")
    ) {
      return "Validation";
    }

    if (
      text.includes("permission") ||
      text.includes("forbidden") ||
      text.includes("unauthorized") ||
      text.includes("blocked")
    ) {
      return "Permission";
    }

    if (
      text.includes("tool") ||
      text.includes("runtime") ||
      text.includes("api") ||
      text.includes("model")
    ) {
      return "Tooling";
    }

    return "Unknown";
  }

  consume(message: string): ErrorDecision {
    this.consumed += 1;
    const category = this.categorize(message);

    return {
      category,
      consumed: this.consumed,
      remaining: Math.max(0, this.budget - this.consumed),
      overBudget: this.consumed > this.budget,
    };
  }

  snapshot() {
    return {
      budget: this.budget,
      consumed: this.consumed,
      remaining: Math.max(0, this.budget - this.consumed),
      over_budget: this.consumed > this.budget,
    };
  }
}

export class ErrorTolerantAgent extends OptimisticMergeAgent {
  private readonly errorPolicy: ErrorPolicy;
  private readonly errorTasks: ErrorTask[] = [];

  constructor(config: AgentConfig & { plannerName?: string; errorBudget?: number }) {
    super(config);
    this.errorPolicy = new ErrorPolicy(config.errorBudget ?? 20);
  }

  override getSystemPrompt(): string {
    return [
      super.getSystemPrompt(),
      "Error policy:",
      "- Never halt on tool/runtime errors.",
      "- Convert every error into a tracked error task.",
      "- Continue with remaining tools and iterations even if budget is exceeded.",
    ].join("\n");
  }

  override getTools(): ToolDefinition[] {
    return [
      ...super.getTools(),
      {
        name: "list_error_tasks",
        description: "List recorded error tasks generated by error policy.",
        input_schema: {
          type: "object",
          properties: {
            status: { type: "string", enum: ["open", "resolved"] },
            limit: { type: "integer" },
          },
        },
      },
      {
        name: "resolve_error_task",
        description: "Mark an error task as resolved.",
        input_schema: {
          type: "object",
          properties: {
            error_task_id: { type: "string" },
          },
          required: ["error_task_id"],
        },
      },
    ];
  }

  private toErrorMessage(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
  }

  private createErrorTask(error: unknown, source: string): ErrorTask {
    const message = this.toErrorMessage(error);
    const decision = this.errorPolicy.consume(message);
    const task: ErrorTask = {
      error_task_id: `err-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      title: `${decision.category} error in ${source}`,
      description: message,
      category: decision.category,
      source,
      status: "open",
      created_at: Date.now(),
      budget_index: decision.consumed,
      over_budget: decision.overBudget,
    };

    this.errorTasks.push(task);
    return task;
  }

  private listErrorTasks(input: Record<string, unknown>): string {
    const status = input.status === "open" || input.status === "resolved" ? input.status : undefined;
    const rawLimit = Number(input.limit ?? 50);
    const limit = Number.isFinite(rawLimit) && rawLimit > 0 ? Math.floor(rawLimit) : 50;

    const selected = this.errorTasks.filter((task) => !status || task.status === status);
    return JSON.stringify(
      {
        policy: this.errorPolicy.snapshot(),
        tasks: selected.slice(-limit),
      },
      null,
      2
    );
  }

  private resolveErrorTask(input: Record<string, unknown>): string {
    const errorTaskId = String(input.error_task_id ?? "").trim();
    if (!errorTaskId) return "Error: missing error_task_id";

    const task = this.errorTasks.find((item) => item.error_task_id === errorTaskId);
    if (!task) return `Error: error task not found: ${errorTaskId}`;

    task.status = "resolved";
    return `Resolved ${errorTaskId}`;
  }

  protected override async processToolCalls(content: ContentBlock[]): Promise<ToolResultBlock[]> {
    const results: ToolResultBlock[] = [];

    for (const block of content) {
      if (block.type !== "tool_use") continue;

      if (block.name === "list_error_tasks") {
        this.emit("tool_call", { name: block.name, input: block.input });
        const output = this.listErrorTasks(block.input as Record<string, unknown>);
        const result: ToolResultBlock = { type: "tool_result", tool_use_id: block.id, content: output };
        results.push(result);
        this.emit("tool_result", {
          tool_use_id: block.id,
          name: block.name,
          content: result.content,
          is_error: false,
        });
        continue;
      }

      if (block.name === "resolve_error_task") {
        this.emit("tool_call", { name: block.name, input: block.input });
        const output = this.resolveErrorTask(block.input as Record<string, unknown>);
        const isError = output.startsWith("Error:");
        const result: ToolResultBlock = {
          type: "tool_result",
          tool_use_id: block.id,
          content: output,
          is_error: isError,
        };
        results.push(result);
        this.emit("tool_result", {
          tool_use_id: block.id,
          name: block.name,
          content: result.content,
          is_error: result.is_error,
        });
        continue;
      }

      try {
        const nestedResults = await super.processToolCalls([block]);
        results.push(...nestedResults);
      } catch (error) {
        const task = this.createErrorTask(error, `tool:${block.name}`);
        const contentText = [
          `Error routed to task ${task.error_task_id}.`,
          `Category: ${task.category}`,
          `Source: ${task.source}`,
          `Over budget: ${task.over_budget}`,
          `Message: ${task.description}`,
        ].join("\n");

        const toolResult: ToolResultBlock = {
          type: "tool_result",
          tool_use_id: block.id,
          content: contentText,
          is_error: true,
        };
        results.push(toolResult);
        this.emit("tool_result", {
          tool_use_id: block.id,
          name: block.name,
          content: toolResult.content,
          is_error: true,
        });
      }
    }

    return results;
  }

  override async run(userMessage: string): Promise<string> {
    this.aborted = false;
    this.messages.push({ role: "user", content: userMessage });
    this.emit("state_change");

    let finalText = "";

    while (this.loopIteration < (this.config.maxIterations || 10)) {
      if (this.aborted) break;
      this.loopIteration += 1;

      let response: Awaited<ReturnType<typeof createMessage>> | null = null;

      try {
        response = await createMessage({
          apiKey: this.config.apiKey,
          model: this.config.model,
          system: this.getSystemPrompt(),
          messages: this.messages,
          tools: this.getTools(),
        });
      } catch (error) {
        const task = this.createErrorTask(error, "llm:create_message");
        const fallback: Message = {
          role: "assistant",
          content: [{ type: "text", text: `LLM error captured as ${task.error_task_id}. Continuing.` }],
        };
        this.messages.push(fallback);
        this.emit("state_change");
        continue;
      }

      this.totalInputTokens += response.usage.input_tokens;
      this.totalOutputTokens += response.usage.output_tokens;
      this.emit("llm_response", { stopReason: response.stop_reason });

      this.messages.push({ role: "assistant", content: response.content });
      this.emit("state_change");

      if (response.stop_reason !== "tool_use") {
        finalText = this.extractText(response.content);
        break;
      }

      let toolResults: ToolResultBlock[] = [];
      try {
        toolResults = await this.processToolCalls(response.content);
      } catch (error) {
        const task = this.createErrorTask(error, "planner:process_tool_calls");
        toolResults = [
          {
            type: "tool_result",
            tool_use_id: "internal-error",
            content: `Error routed to ${task.error_task_id}. Continuing without halt.`,
            is_error: true,
          },
        ];
      }

      this.messages.push({ role: "user", content: toolResults });
      this.emit("state_change");
    }

    if (!finalText && this.errorTasks.length > 0) {
      finalText = `Completed with ${this.errorTasks.length} error task(s). Review with list_error_tasks.`;
    }

    this.emit("done", { text: finalText, iterations: this.loopIteration });
    return finalText;
  }

  override getState(): AgentState {
    return {
      ...super.getState(),
      errorPolicy: this.errorPolicy.snapshot(),
      errorTasks: this.errorTasks,
    } as AgentState;
  }
}
